language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - python -m grpc.tools.protoc -I=protobuf --python_out=bci/protocol sample.proto
script:
#  - flake8
  - pytest --cov-report term --cov=bci
after_success:
  - codecov
services:
  - docker
before_install:
- docker pull rabbitmq
- docker run -d -p 2222:5672 rabbitmq
- docker pull postgres
- docker run -d -e POSTGRES_PASSWORD=password -e POSTGRES_USER=test -p  3333:5432 postgres
