version: "3.7"

services:
  rabbitmq-test:
    image: "rabbitmq"
    ports:
      - "2222:5672"
  db-test:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "test"
    ports:
      - "3333:5432"
