# CLI Defaults
DEFAULT_QUIET = False
DEFAULT_TRACEBACK = False

# Reader Defaults
DEFAULT_FORMAT = 'protobuf'

# Server Defaults
DEFAULT_SERVER_HOST = '127.0.0.1'
DEFAULT_SERVER_PORT = 8000

# RabbitMQ Server Defaults
DEFAULT_RABBITMQ_SERVER_HOST = '127.0.0.1'
DEFAULT_RABBITMQ_SERVER_PORT = 5672

# PostgreSQL Server Defaults
DEFAULT_POSTGRESQL_SERVER_HOST = '127.0.0.1'
DEFAULT_POSTGRESQL_SERVER_PORT = 5432

# Default Database
DEFAULT_DATABASE = f'postgresql://{DEFAULT_POSTGRESQL_SERVER_HOST}:' \
                   f'{DEFAULT_POSTGRESQL_SERVER_PORT}'

# API Server Defaults
DEFAULT_API_SERVER_HOST = '127.0.0.1'
DEFAULT_API_SERVER_PORT = 5000

# Web Server Defaults
DEFAULT_WEB_SERVER_IP = '127.0.0.1'
DEFAULT_WEB_SERVER_PORT = 8080
